### ISSUE TITLE
Number of out-of-date packages in exit code

### ISSUE THREAD

**Issue by simon04** [simon04/aur-out-of-date#12]
Exit the program with exit code `n=0…254` if `n` packages are out-of-date. Keep 255 for other errors.

**Comment by AladW** [comment]
What if >254 packages are out of date? (That might sound an absurd scenario, but there are indeed users with over 1000 AUR packages...)

**Comment by eli-schwartz** [comment]
Exit codes are meant to tell you the status of the program's own functionality, not provide you information obtained by the package. If you want to script things, #11 should allow machine-parseable output in e.g. json which would be a far, far superior solution IMHO.

**Comment by simon04** [comment]
This is not universally true. Some counter examples are grep, pgrep, cmp, all monitoring-plugins.

**Comment by eli-schwartz** [comment]
I'm a bit confused there, AFAIK grep only returns 0 if matches were found and 1 if matches were not found (which is an internal "success vs failure" state), can you explain in which situations grep will return an exit code of e.g. 4 for "four matches found"?

> EXIT STATUS
>> Normally  the  exit  status  is  0  if  a line is selected, 1 if no lines were selected, and 2 if an error occurred.  However, if the -q or --quiet or --silent is used and a line is selected, the exit status is 0 even if an error occurred.

Having different non-zero exit codes to distinguish between command failure due to the program's objective not being met ("find matching text") vs. command failure due to invalid input, is pretty normal. That is pretty different from what is being suggested here, which is to pass actual data responses encoded in the exit "status".

**Comment by simon04** [comment]
Agreed. So I should rephrase this enhancement to exit with a fixed non-zero code if at least one package has been determined out-of-date.

**Comment by eli-schwartz** [comment]
Yes, that would be reasonable.
