### ISSUE TITLE
Compare local files

### ISSUE THREAD

**Issue by AladW** [simon04/aur-out-of-date#4]
Perhaps it may be useful to also check local PKGBUILDs for updates, rather than only the AUR RPC. 

An alternative is to allow taking version information from `stdin` or a file, such that `aur-of-date`'s ability to query VCS hosters' API can be used flexibly.

**Comment by eli-schwartz** [comment]
It would make this more generically useful, if it did not have a hardcoded dependency on aur.archlinux.org

cf. modular AUR helpers like [aurutils](https://github.com/AladW/aurutils/).

Example workflow: user has a directory $dir, containing a number of subdirectories where each one has a PKGBUILD and .SRCINFO. `aur-out-of-date -local $dir/*/.SRCINFO` would check the .SRCINFO files on disk rather than downloading a .SRCINFO from https://aur.archlinux.org/cgit/

Alternatively, `aur-out-of-date -local $dir` by processing each subdirectory would allow mixing and matching different types in one command execution. But currently this doesn't allow that for -user and -pkg.

**Comment by simon04** [comment]
So the (main) use-case for this would be to run the tool on a repository/directory like https://github.com/eli-schwartz/pkgbuilds?

**Comment by eli-schwartz** [comment]
Yes.

**Comment by simon04** [comment]
Local files are supported now. Note that the tool does not implement/provide globbing itself, but relies on the shell to expand `*` and alike.

```
$ aur-out-of-date -local packages/*/.SRCINFO
```

**Comment by eli-schwartz** [comment]
Thanks, this makes sense and seems to work quite nicely.
